#!/usr/bin/perl

@processes = `pgrep -lf "firstclass2imap.pl"`;

foreach $process (@processes) {
  if (($process =~ /^(.* firstclass2imap.pl\s+)(\d+)/) && ($2 ne "")) {
    $fromuser = `awk 'END{print \$NF}' /var/log/migration/instance.$2`;
    chomp($fromuser);
    print "$1 $2 $fromuser\n";
 }
}
